#include "Arduino.h"
  String getMainPage()
  {
    String response = "<html><head>"
      "<script "
      "src=\"https://code.jquery.com/jquery-3.2.1.js\" "
      "integrity=\"sha256-DZAnKJ/6XZ9si04Hgrsxu/8s717jcIzLy3oi35EouyE=\" "
      "crossorigin=\"anonymous\"></script> "
     "<script type=\"text/javascript\" "
    "src=\"https://www.gstatic.com/charts/loader.js\"></script> "

    "</head> "
    "<body> "
      "<div id=\"chart_div\" style=\"width: 600px; height: 300px;\"></div> "
      "<script type=\"text/javascript\"> "
      "$( document ).ready(function(){ "
        "google.charts.load('current', {'packages':['gauge']}); "
        "google.charts.setOnLoadCallback(drawChart); "

        "function drawChart() { "
          "var data = "
            "google.visualization.arrayToDataTable([ "
              "['Label', 'Value'], "
              "['Temp', 0.00], "
              "['Temp', 0.00] "
            "]); "
          "var options = { "
            "width: 600, "
            "height: 300, "
            "redFrom: 90, "
            "redTo: 100, "
            "yellowFrom:75, "
            "yellowTo: 90, "
            "minorTicks: 5 "
          "}; "
          "var chart = new google.visualization.Gauge(document.getElementById('chart_div')); "
          "chart.draw(data, options); "
          "setInterval(function() { "
            "var jqxhr = $.get( \"/get-temp/\", function(value) { "
              "data.setValue(0, 1, value.probeA); "
              "data.setValue(1, 1, value.probeB); "
              "},\"json\"); "
                "chart.draw(data, options); "
              "}, 15000); "
        "} "
      "}); "
      "</script> "
    "</body></html>";
    return response;
  }
